version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  assignees:
  - jschloer
  labels:
  - dependencies
  ignore:
  - dependency-name: "@types/*"
    versions:
    - ">= 0"
  - dependency-name: "@babel/runtime"
    versions:
    - 7.12.13
    - 7.12.17
    - 7.12.18
    - 7.12.5
    - 7.13.0
    - 7.13.1
    - 7.13.10
    - 7.13.17
    - 7.13.2
    - 7.13.4
    - 7.13.6
    - 7.13.7
    - 7.13.8
    - 7.13.9
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.1
    - 7.13.10
    - 7.13.13
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: react
    versions:
    - 17.0.1
- package-ecosystem: npm
  directory: "/example"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  assignees:
  - jschloer
  labels:
  - dependencies
  - example
  ignore:
  - dependency-name: "@types/*"
    versions:
    - ">= 0"
  - dependency-name: react-scripts
    versions:
    - 4.0.1
  - dependency-name: react-dom
    versions:
    - 17.0.1
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: handlebars
    versions:
    - 4.7.6
